C:\cwRsync\bin\rsync -avrltc --progress --chmod=u=rwx,g=rx,o=rx --delete  /cygdrive/d/workspace/MyBlog/pyblog/* pyshell@115.126.86.67::pyblog/ --password-file=/cygdrive/d/workspace/MyBlog/pyblog/pyblog.pass

pause ...